---
title: 'Assignment 2: Sentiment Analysis I'
author: "Paloma Cartwright"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

librarian::shelf(here, janitor, LexisNexisTools, lubridate, pdftools, readr, sentimentr, tidyr, tidytext, tidyverse)

```

# Read in the Lexus Nexis file for "Sea Level Rise"

```{r, message=FALSE}
my_files <- list.files(pattern = ".docx", path = getwd(),
                       full.names = TRUE, recursive = TRUE, ignore.case = TRUE)

dat <- lnt_read(my_files[2]) #Object of class 'LNT output'


meta_df <- dat@meta
articles_df <- dat@articles
paragraphs_df <- dat@paragraphs

dat2 <- data_frame(element_id = seq(1:length(meta_df$Headline)), 
                   Date = meta_df$Date, Headline = meta_df$Headline) 

paragraphs_dat <- data_frame(element_id = paragraphs_df$Art_ID, 
                             Text  = paragraphs_df$Paragraph)

dat3 <- inner_join(dat2, paragraphs_dat, by = "element_id") %>% clean_names()

dat3 <- dat3[!grepl("http", dat3$text),]
dat3 <- subset(dat3, text != " ")
dat3 <- dat3[!grepl("Article Rating", dat3$text),]
dat3 <- dat3[!grepl("--IANS", dat3$text),]
dat3 <- dat3[!duplicated(dat3$text),]
dat3 <- dat3[!grepl("From AR6:", dat3$text),]
dat3 <- dat3[!grepl("ksk/", dat3$text),]
dat3 <- dat3[!grepl("Contact", dat3$text),]


dat3 <- dat3[!grepl(" - ", dat3$text),]

dat3 <- dat3[!grepl("Apr 0", dat3$text),]
dat3 <- dat3[!grepl("Mar 0", dat3$text),]
dat3 <- dat3[!grepl("Feb 0", dat3$text),]
dat3 <- dat3[!grepl("Jan 0", dat3$text),]

dat3 <- dat3 %>% 
  drop_na()

```

# Calculate the Polarity of the Headlines 

```{r}
mytext <- get_sentences(dat2$Headline)
sent <- sentiment(mytext)

sent_df <- inner_join(dat2, sent, by = "element_id")

sentiment <- sentiment_by(sent_df$Headline)

sent_df %>%
  arrange(sentiment)

sent_df$polarity <- ifelse(sent_df$sentiment < 0, -1, ifelse(sent_df$sentiment > 0, 1, 0))

sent_df <- sent_df %>% 
  mutate(polarity = factor(polarity, levels = c("1", "0", "-1"))) %>% 
  clean_names()
 
sent_df_group <- sent_df %>% 
  count(polarity, date) %>% drop_na()
```

## Create a PLot of Sentiment Data Polarity 

```{r}
ggplot(data = sent_df_group, aes(x = date, y = n, color = polarity)) + 
  geom_line() + 
  labs(y = "Number of Headlines",
       x = "Date",
       color = "Sentiment") + 
  scale_color_manual(values = c("blue", "gray", "red"),
                     labels = c("Positive", "Neutral", "Negative")) + 
  theme_classic()
```

# Unnext Data into Words

```{r}
bing_sent <- get_sentiments('bing')

#unnest to word-level tokens, remove stop words, and join sentiment words
text_words <- dat3  %>%
  unnest_tokens(output = word, input = text, token = 'words') %>% 
  anti_join(stop_words, by = 'word') %>% 
  inner_join(bing_sent, by = "word") 

```


```{r}
sent_score <- text_words %>% 
  count(sentiment, date) %>% 
  spread(sentiment, n) 

sent_score[is.na(sent_score)] <- 0

sent_score <- sent_score %>% 
  mutate(raw_score = positive - negative, 
         offset = mean(positive - negative), 
         offset_score = (positive - negative) - offset) %>% 
  arrange(desc(raw_score))
```


```{r}

ggplot(sent_score, aes(x = date)) +
  geom_bar(aes(y = raw_score), stat = 'identity', fill = 'slateblue3') +
  geom_bar(aes(y = offset_score), stat = 'identity', fill = 'red4') +
  geom_hline(yintercept = sent_score$offset[1], linetype = 'dashed', size = .5) +
  theme_classic() +
  theme(axis.title.y = element_blank()) +
  labs(title = 'Sentiment analysis: Sea Level Rise',
       y = 'Sentiment score')
```


# Perform Sentiment Analysis using the NRC Sentiment Words

```{r}

nrc_sent <- get_sentiments('nrc')

nrc_sent_counts <- dat3  %>%
  unnest_tokens(output = word, input = text, token = 'words') %>% 
  inner_join(nrc_sent) %>%
  count(word, sentiment, date, sort = TRUE) %>%
  ungroup()
 
nrc_sent_counts <- subset(nrc_sent_counts, !(sentiment %in% c("positive", "negative")))

nrc_sent_graph <- nrc_sent_counts %>% 
  group_by(sentiment) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(n, word, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(x = "Contribution to sentiment",
       y = NULL)

nrc_sent_graph

```

# Calculating the Distribution of Sentiment

```{r}
 
nrc_sent_counts2 <- nrc_sent_counts %>% 
  group_by(date, sentiment) %>% 
  summarise(total_n = sum(n)) %>% 
  spread(sentiment, total_n) %>% 
  ungroup()

nrc_sent_counts2[is.na(nrc_sent_counts2)] = 0

nrc_sent_counts2 <- nrc_sent_counts2 %>% 
  mutate(totals = anger + anticipation + disgust + fear + joy + sadness + surprise + trust)

nrc_sent_counts2 <- nrc_sent_counts2 %>% 
  pivot_longer(cols = !c("date", "totals"), names_to = "sentiment", values_to = "n")
#calculate the %
nrc_sent_counts2 <- nrc_sent_counts2 %>% 
  mutate(percentage = n / totals)
```

# Daily Percentage of Sentiment Words 

```{r}
ggplot(data = nrc_sent_counts2, aes(x = date, y = percentage, color = sentiment)) + 
  #geom_point(alpha = 0.25) +
  geom_smooth(method = lm, se = FALSE) + 
  theme_classic() + 
  labs(x = "Date (2022)", 
       y = "Daily Percentage of Sentiment", 
       color = "Sentiment", 
       title = "Sentiment Analysis of Sea Level Rise") 
```


